config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  
  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  get '/edit', to: 'users#edit'

  post '/signup', to: 'users#create'

  resources :users do
    resources :books, only: [:index, :show]
  end

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :books do
   member do
    patch :finish
    patch :cancel
    get :info
   end
  end

  get '/edit', to: 'books#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord 
    def finished?
        !finished_at.blank?
    end
    enum status: { started: 0, reading: 1, finished: 2, cancelled: 3 } do
    
    event :start do
        after do
        self.started_at = DateTime.now
        self.save
        end
        transition :started => :reading
    end
    event :cancel do
        after do
         self.cancelled_at = DateTime.now
         self.save
        end
        transition :started => :cancelled
    end
    event :finish do
        after do
         self.finished_at = DateTime.now
         self.save
        end
        transition :reading => :finished
    end
    end
    belongs_to :user
    belongs_to :category
    default_scope -> { order(created_at: :desc) }
    mount_uploader :cover, CoverUploader
    validates :user_id, presence: true
    validates :title, presence: true
    validates :author, presence: true
    validates :category, presence: true
    validates :cover, presence: false
    validate :cover_size

    def time_reading(param1, param2 = Time.now)
        time_diff = (param2 - param1)
        return (time_diff / 1.day).round
    end     

    private
    def cover_size
        if cover.size > 1.megabytes
            errors.add(:cover, "should be less than 1 MB")
        end
    end
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :books
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books, dependent: :destroy  
    before_save { email.downcase! }
    validates :username, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true      
    
    def feed
       Book.where("user_id = ?", id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
  	render html: "Hello!"
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy
    # before_action :set_cancelled_at_to_now, only: :create

    
    def index
        if params[:category].blank?
         @books = Book.all
        else
          @category = Category.find_by(name: params[:category])  
          @category_id = Category.find_by(name: params[:category]).id
          @books = current_user.books.where(category_id: @category_id)
        end
    end
    def show

    end
    
    def create
        @book = current_user.books.build(book_params)
        @book.start!
        if @book.save
            flash[:success] = "Book added!"
            redirect_to root_url
        else
            @feed_items = []
           render 'static_pages/home' 
        end
    end

    def edit
         @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if @book.update_attributes(book_params)
            flash[:success] = "Book updated!"
            redirect_to root_url
        else
            render 'edit'
        end
        
    end

    def destroy
        @book.destroy
        flash[:success] = "Book deleted"
        redirect_to request.referrer || root_url
    end

    def finish
        @book = Book.find(params[:id])
        @book.update_attributes(status: 2)
        @book.update_attributes(finished_at: Time.now)
        flash[:success] = "Book finished!"
        redirect_to root_path
    end

    def cancel
        @book = Book.find(params[:id])
        @book.update_attributes(status: 3)
        @book.update_attributes(cancelled_at: Time.now)
        flash[:success] = "Book not finished :("
        redirect_to root_path
    end
    def info
        @book = Book.find(params[:id])
    end

    private
    def book_params
        params.require(:book).permit(:title, :author, :category_id, :status, :cover)        
    end

    def correct_user
        @book = current_user.books.find_by(id: params[:id])
    end
    # def set_cancelled_at_to_now 
    #     @book.params(:cancelled_at).Time.now         
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
      #redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
       @book = current_user.books.build
       @feed_items = current_user.feed.paginate(page: params[:page])
    end
   
  end

  def about
  end

  def contact
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]




  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.paginate(page: params[:page])
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Bibliodarium"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  # confirma un usuario loggueado
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
    
  #  def selected_book
     #   @book = current_user.books.find_by(id: )
  #  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id 
    end
    def logged_in?
        !current_user.nil?
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def current_user?(user)
        user == current_user
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil 
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.username, class: "gravatar")
        
    end
end

app/views/books/_book.html.erb
<li id="book-<%= book.id %>">

    <% if book.status == 'reading' %>

    <h3 class="title"><%= book.title %> <small>(current reading)</small> </h3>
    <span class="author"><%= book.author %> </span><br>
    <small class=""><%= book.category.name if book.category%></small><br>
    <span class="timestamp">
    <% if book.started_at.nil? %>
        <small><%= book.status %></small>
        <% if current_user?(book.user) %>
            <%= link_to "delete", book, method: :delete,
                                             data: { confirm: "Seguro?" } %> |
                                            <%= link_to "edit", edit_book_path(id: book) %> |
                                            <%= link_to "mark as finished", finish_book_path(book), method: :patch %> |
                                            <%= link_to "cancel", cancel_book_path(book), method: :patch %>
        <% end %> 
    <% else  %>
        <small> Started <%= time_ago_in_words(book.started_at) %> ago. </small>
        <% if current_user?(book.user) %>
            <%= link_to "delete", book, method: :delete,
                                             data: { confirm: "Seguro?" } %> |
                                            <%= link_to "edit", edit_book_path(id: book) %> |
                                            <%= link_to "mark as finished", finish_book_path(book), method: :patch %> |
                                            <%= link_to "cancel", cancel_book_path(book), method: :patch %> |
                                            <%= link_to "info", info_book_path(book.id), class: "link" %>
        <% end %> 
    <% end %>
    </span>

    <% elsif book.status == 'finished' %>

    <h3 class="title"><%= book.title %></h3>
    <span class="author"><%= book.author %> </span><br>
    <small class=""><%= book.category.name if book.category%></small><br>
    <span class="timestamp">
    <% if book.started_at.nil? %>
      <small><%= book.status %></small>
        <% if current_user?(book.user) %>
            <%= link_to "delete", book, method: :delete,
                                             data: { confirm: "Seguro?" } %> |
                                            <%= link_to "edit", edit_book_path(id: book) %>
        <% end %> 
    <% else %>
        <small> Finished <%= time_ago_in_words(book.finished_at) %> ago. </small>
        <% if current_user?(book.user) %>
            <%= link_to "delete", book, method: :delete,
                                             data: { confirm: "Seguro?" } %> |
                                            <%= link_to "edit", edit_book_path(id: book) %> |
                                            <%= link_to "info", info_book_path(book.id), class: "link" %>
        <% end %> 

    <% end %>
    </span>

    <% else %>
    <h3 class="title books-cancelled"><%= book.title %></h3>
    <span class="author books-cancelled"><%= book.author %> </span><br>
    <small class="books-cancelled"><%= book.category.name if book.category%></small><br>
    <span class="timestamp books-cancelled">
    <% if book.status.nil? %>
      <small class="books-cancelled"><%= book.status %> <%= time_ago_in_words(book.cancelled_at) %> ago.</small>
        <% if current_user?(book.user) %>
            <%# link_to "delete", book, method: :delete,
                                             data: { confirm: "Seguro?" } %> 
                                            <%# link_to "edit", edit_book_path(id: book) %>
        <% end %>
    <% else %>
        

        <small class="books-cancelled"><%= book.status %></small>
   
        
        <% if current_user?(book.user) %>
            <%# link_to "delete", book, method: :delete,
                                             data: { confirm: "Seguro?" } %> 
                                            <%# link_to "edit", edit_book_path(id: book) %>
        <% end %> 

    <% end %>
    </span>
    <% end %>
</li>

app/views/books/_edit_form.html.erb
<%= form_for(@book) do |b| %>

    <%= render 'shared/error_messages', object: b.object %>
    
    <%= b.label :title %>
    <%= b.text_field :title, class: 'form-control' %>

    <%= b.label :author %>
    <%= b.text_field :author, class: 'form-control' %>
    
    <%= b.collection_select(:category_id, Category.all, :id, :name, :prompt => "Select an category") %>
    
    <span class="cover">
        <%= b.file_field :cover, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    
    <%= b.submit yield(:button_text), class: 'btn btn-primary' %>

<% end %>

app/views/books/edit.html.erb
<%= provide(:title, "Edit book") %>
<%= provide(:button_text, "Save changes") %>

<div class="row">

<div class="col-md-10 col-md-offset-1 edit">
<h1>Edit book</h1>
        <div class="col-md-6 col-md-offset-3">
            <%= render 'edit_form' %>
        </div>

    </div>
</div>

app/views/books/index.html.erb
<% provide(:title, @category.name ) %>
<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
    <aside class="col-md-4 withoutPad center">
        <section class="user_info">
            <h1>
                <%= gravatar_for current_user %>
                <%= current_user.username %>
            </h1>
        </section>
    </aside>

    <div id="user-show" class="col-md-8">
      
        <% if @books.any? %>
        <h3>Books of <%= @category.name %> (<%= @books.count %>)</h3>
            <ol style="list-style: none" class="books">
                <%= render @books %>
            </ol> 
        <% else %>
        <li class="dropdown" style="list-style: none">
         <h3>Books of <%= @category.name %> (<%= @books.count %>)</h3>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" roles="menu">
            <li><%= link_to "All", user_path(current_user) %></li>
            <% Category.all.each do |category| %>
                <li>
                   <%= link_to category.name, user_books_path(current_user.id, category: category.name), class: "link" %>
                </li>
            <% end %>
            </ul>
        </li>
        
        <% end %>

    </div>

    </div>
    <div class="col-md-1">

    </div>
</div>

app/views/books/info.html.erb
<% provide(:title, @book.title ) %>
<div class="col-md-1">

</div>
<div class="col-md-10 withoutPad">
   
    <div class="center">
        <h3><strong><%= @book.title %></strong></h3>
        <%= image_tag @book.cover.url if @book.cover? %>
        <h4><%= @book.category.name %></h4>
        <h3>State: </h3> <p> <%= @book.status %></p> 
    </div>
    <% if @book.finished? %>
        <div id="fechas-info-book">
            <h3>Started at: </h3>
            <p> <%= @book.created_at.strftime("%d-%B-%y at %I:%M%p") %> </p>
            <h3>Finished at: </h3>
            <p> <%= @book.updated_at.strftime("%d-%B-%y at %I:%M%p") %> </p>
            <h3>Reading time: </h3>
            <p> <%= @book.time_reading(@book.started_at, @book.finished_at) %> days </p>
        </div>
    <% else %>
        <div id="fechas-info-book">
            <h3>Started at: </h3>
            <p> <%= @book.created_at.strftime("%d-%B-%y at %I:%M%p") %> </p>
            <h3>Timing: </h3>
            <p> <%= @book.time_reading(@book.started_at) %> days </p>
        </div>
    <% end %>
    
    
    <div id="author-info-book">
        <h3>Author: </h3> <p><%= @book.author %></p> 
    </div>
</div>
<div class="col-md-1">

</div>

app/views/layouts/_footer.html.erb
<footer class="navbar-fixed-bottom footer">
<div  class="container">
    
    <div class="row">

        <div class="col-md-1">

        </div>

        <div id="container-footer" class="col-md-10">
            <small>
                Made with a lots of spells by <a href="http://www.twitter.com/jizabard"> Izabard</a>
            </small>
            <nav>
                <ul>
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                </ul>
            </nav>
        </div>

        <div class="col-md-1">

        </div>

    </div>

</div>

</footer>

app/views/layouts/_header.html.erb
<header id="header" class="navbar navbar-fixed-top navcontent">

      <div class="container">
       
      <div class="row">

      <div class="col-md-1">
      </div>

        <div class="col-md-10">
          
          <nav id="mynavwithoutdefaultclass" class="navbar navbar-default navbar-light bg-light">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>              
              </button>
              <%= link_to "Bibliodarium", root_path, id: "logo" %>
            </div>
            
            <div class="collapse navbar-collapse" id="main-nav-collapse">
              <ul class="navbar-nav navbar-right nav">
              <li><%= link_to "Home", root_path %></li>
                <% if logged_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: :delete %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
            </div>
          </nav>
        </div>
        
        <div class="col-md-1">
        </div>
       </div>
      
       </div>
</header>

app/views/layouts/_message.html.erb
<div class="col-md-1">

</div>
<div class="col-md-10 space">
    <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
</div>
<div class="col-md-1">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Bibliodarium </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                             'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    
    <%= render 'layouts/header' %>
    <%= render 'layouts/message' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_book_form.html.erb
<%= form_for(@book) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.label :Title %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :Author %>
        <%= f.text_field :author, class: 'form-control' %>

        <%= f.collection_select(:category_id, Category.all, :id, :name, :prompt => "Select an category") %>
    </div>
    <%= f.submit "Añadir", class: "btn btn-primary" %>
    <span class="cover">
        <%= f.file_field :cover, accept: 'image/jpeg, image/gif, image/png' %>
    </span>
<% end %>

<script type="text/javascript">
    $('#book_picture').bind('change', function(){
        var size_in_megabytes = this.files[0].size/1024/1024;
        if(size_in_megabytes > 1){
            alert('Maximum file size is 1MB. Please choose a smaller file.');
        }
    });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_user_info.html.erb
<div class="center">
    <div class="col-md-4 user_gravatar">
        <%= link_to gravatar_for(current_user, size: 50), current_user %>
    </div>

    <section class="col-md-8 user_info">
        <li>
            <h2> <%= current_user.username %> </h2>
        </li>
        <li>
            <small><%= link_to "view my profile", current_user %></small>
        </li>
        <li>
            <small><%= pluralize(current_user.books.count, "book") %></small>  
        </li>
   </section>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
    
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
    <h1>About</h1>    
        <h3>This is a personal little project dedicated to mantain a books control. </h3>
        <h3 class="about-text">Along side by this app there is a course that made possible to do this project: <br><a href="https://www.railstutorial.org/">The Rails Tutorial</a> by Michael Hartl.</h3>
        <h3>Technologies used in this project:</h3>    
            <ul id="items-technologies">
                <li>
                    <h3>
                        PostgreSQL
                    </h3>
                </li>
                <li>
                    <h3>
                        ruby 2.4.0p0
                    </h3>
                </li>
                <li>
                    <h3>
                        Rails 5.1.4
                    </h3>
                </li>
            <ul>
        </h2>
    
    </div>

    <div class="col-md-1">
    </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<div class="row">
    <div class="col-md-1">
    
    </div>
    
    <div class="col-md-10">
        <h1>Contact</h1>    

            <div class="contact-text col-md-9">
                <h2 id="first-p-contact">Hello,</br> If you want to send me any question or suggestion <a href="mailto:izaba97@gmail.com">here</a> my email :) </h2>
            </div>
            <div class="contact-text col-md-9">
                <h2>You can also check my networks too ;) </h2>
            </div>
            
            <div id="social-icons" class="col-md-6 col-md-offset-3">
                <div class="col-xs-4 center">
                    <a href="https://github.com/izabard"><i class="fab fa-github icons"></i></a>        
                </div>            
                <div class="col-xs-4 center">
                    <a href="http://www.twitter.com/jizabard"><i class="fab fa-twitter icons"></i></a>
                </div>
                    <div class="col-xs-4 center">
                    <a href="https://www.instagram.com/iluvala"><i class="fab fa-instagram icons"></i></a>
                </div>
            </div>

                       
              
    </div>

    <div class="col-md-1">
    
    </div>

</div>
   

app/views/static_pages/home.html.erb
<%= provide(:title, "Home") %>
<% if logged_in? %>
    <div class="row">

        <div class="col-md-1">

        </div>
            
        <div class="col-md-10">
            <aside id="aside-pad" class="col-md-4">
                <section class="aside_user_info">
                    <%= render 'shared/user_info' %>
                </section>
                <section class="book_form">
                    <%= render 'shared/book_form' %>
                </section>
            </aside>
            
            <div class="col-md-7 col-md-offset-1 feed">
                <h3 id="h3-first">Books Feed</h3>
                <%= render 'shared/feed' %>
            </div>
        </div>
        
        <div class="col-md-1">

        </div>
  
    </div>  
<% else %>
    <div class="row">
    
    <div class="col-md-1">
    </div>

    <div class="col-md-10 ">
        <h1>Welcome to Bibliodarium</h1>
        <%= link_to "Sign up", signup_path, class: ""%>
    </div>

    <div class="col-md-1">
    </div>
    
    </div>
    
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :username %>
            <%= f.text_field :username, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
            
<% end %>

app/views/users/edit.html.erb
<%= provide(:title, "Edit user") %>
<%= provide(:button_text, "Save changes") %>

<div class="row">
    <div class="col-md-1">

    </div>

    <div class="col-md-10">
    <h1>Edit your profile</h1>
        <div class="col-md-6 col-md-offset-3">
            <%= render 'form' %>
        </div>
    </div>
        
    <div class="col-md-1">

    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up')%>
<%= provide(:button_text, 'Create my account') %>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
            <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username )  %>
<div class="row">
    <div class="col-md-1">

    </div>
        <div class="col-md-10">
            <aside class="col-md-4 withoutPad center">
                <section class="user_info">
                    <h1>
                        <%= gravatar_for @user %>
                        <%= @user.username%>
                    </h1>
                </section>
            </aside>
            <div id="user-show" class="col-md-8">
                <% if @user.books.any? %>
                    <h3>Books (<%= @user.books.count %>) </h3>
                    
                   <li class="dropdown" style="list-style: none">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
                    <ul class="dropdown-menu" roles="menu">
                        <% Category.all.each do |category| %>
                        <li>
                        <%= link_to category.name, user_books_path(user_id: params[:id], category: category.name), class: "link" %>
                        </li>
                        <% end %>
                    </ul>
                   </li>
                    
                    <ol class="books">
                        <%= render @books %>
                    </ol>
                    <%= will_paginate @books %>
                <% end %>
                
            </div>

        </div>
    <div class="col-md-1">
    </div>
</div>